# Generated by Django 5.2.17 on 2026-09-29 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('reset_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rate_limits',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('phone', models.TextField(primary_key=True, serialize=False)),
                ('chat_id', models.TextField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'telegram_links',
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('purpose', models.TextField()),
                ('channel', models.TextField(default='sms')),
                ('code_hash', models.TextField(blank=True, null=True)),
                ('start_token', models.TextField(blank=True, null=True, unique=True)),
                ('tg_chat_id', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'otp_codes',
                'indexes': [models.Index(fields=['phone', 'purpose', '-created_at'], name='idx_otp_phone')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purpose__in', ['register', 'reset'])), name='otp_codes_purpose_check'), models.CheckConstraint(condition=models.Q(('channel__in', ['sms', 'telegram', 'dev'])), name='otp_codes_channel_check')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('password_hash', models.TextField()),
                ('role', models.TextField(choices=[('user', 'Mijoz'), ('master', 'Usta'), ('admin', 'Administrator')], default='user')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['user', 'master', 'admin'])), name='users_role_check')],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('specialty', models.TextField()),
                ('district', models.TextField()),
                ('experience_years', models.IntegerField(default=0)),
                ('bio', models.TextField(default='')),
                ('jobs_done', models.IntegerField(default=0)),
                ('status', models.TextField(choices=[('pending', 'Tekshiruvda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.TextField(default='samarqand')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to='core.user')),
            ],
            options={
                'db_table': 'masters',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.TextField(unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('room_type', models.TextField()),
                ('quality', models.TextField()),
                ('input_json', models.TextField()),
                ('result_json', models.TextField()),
                ('total', models.FloatField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('ai_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.TextField(default='samarqand')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='core.user')),
            ],
            options={
                'db_table': 'estimates',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('message', models.TextField(default='')),
                ('status', models.TextField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='new')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='core.estimate')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.master')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='core.user')),
            ],
            options={
                'db_table': 'contact_requests',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.user')),
            ],
            options={
                'db_table': 'sessions',
                'indexes': [models.Index(fields=['user'], name='idx_sessions_user')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.user')),
            ],
            options={
                'db_table': 'reviews',
                'constraints': [models.UniqueConstraint(fields=('master', 'user'), name='reviews_master_id_user_id_key'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='reviews_rating_check')],
            },
        ),
        migrations.CreateModel(
            name='PlanOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField()),
                ('amount', models.IntegerField()),
                ('comment', models.TextField(default='')),
                ('status', models.TextField(choices=[('new', 'Yangi'), ('paid', "To'langan"), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='new')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt', models.TextField(blank=True, null=True)),
                ('receipt_at', models.DateTimeField(blank=True, null=True)),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.estimate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.user')),
            ],
            options={
                'db_table': 'plan_orders',
                'constraints': [models.CheckConstraint(condition=models.Q(('plan__in', ['pdf', 'design3d'])), name='plan_orders_plan_check'), models.CheckConstraint(condition=models.Q(('status__in', ['new', 'paid', 'done', 'cancelled'])), name='plan_orders_status_check')],
            },
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['status', 'specialty', 'district'], name='idx_masters_status'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['region', 'status'], name='idx_masters_region'),
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='masters_status_check'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['user', '-created_at'], name='idx_estimates_user'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['master', '-created_at'], name='idx_requests_master'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['phone', '-created_at'], name='idx_requests_phone'),
        ),
        migrations.AddConstraint(
            model_name='contactrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'contacted', 'done', 'cancelled'])), name='contact_requests_status_check'),
        ),
    ]
