# Generated by Django 5.2.17 on 2026-09-29 16:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_key', models.TextField(unique=True)),
                ('category', models.TextField(default='dekor')),
                ('unit', models.TextField(default='dona')),
                ('times_requested', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_requested_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'catalog_requests',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_key', models.TextField(unique=True)),
                ('category', models.TextField(choices=[('material', 'Qurilish materiali'), ('mebel', 'Mebel'), ('texnika', 'Maishiy texnika'), ('santexnika', 'Santexnika'), ('yoritish', 'Yoritish va elektr'), ('dekor', "Dekor va to'qimachilik"), ('ish', 'Usta ishi')])),
                ('unit', models.TextField()),
                ('price', models.IntegerField()),
                ('price_min', models.IntegerField(blank=True, null=True)),
                ('price_max', models.IntegerField(blank=True, null=True)),
                ('quality', models.TextField(default='standard')),
                ('source_name', models.TextField(default='')),
                ('source_url', models.TextField(default='')),
                ('origin', models.TextField(choices=[('seed', "Boshlang'ich baza"), ('ai', 'AI qidiruvi'), ('admin', 'Administrator')], default='seed')),
                ('verified', models.BooleanField(default=True)),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'catalog_items',
                'indexes': [models.Index(fields=['category', 'quality'], name='idx_catalog_category')],
            },
        ),
        migrations.CreateModel(
            name='RoomDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.TextField(unique=True)),
                ('photo', models.TextField()),
                ('area', models.FloatField()),
                ('height', models.FloatField(default=2.7)),
                ('room_type', models.TextField(default='auto')),
                ('budget', models.TextField(default='standard')),
                ('region', models.TextField(default='samarqand')),
                ('wishes', models.TextField(default='')),
                ('status', models.TextField(choices=[('processing', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('failed', 'Xato')], default='processing')),
                ('error', models.TextField(default='')),
                ('plan_json', models.TextField(blank=True, null=True)),
                ('total', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='core.user')),
            ],
            options={
                'db_table': 'room_designs',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_designs_user')],
            },
        ),
    ]
