# Generated by Django 5.2.17 on 2026-09-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_catalog_and_designs'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='image_credit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='doors',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='groups',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='mode',
            field=models.TextField(default='tez'),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='windows',
            field=models.IntegerField(default=1),
        ),
    ]
