# Generated by Django 5.2.17 on 2026-09-29 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_catalog_json_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('kind', models.TextField(choices=[('bonus', "Ro'yxatdan o'tish bonusi"), ('purchase', 'Tarif xaridi'), ('withdraw', 'Pul yechish'), ('refund', 'Qaytarildi'), ('admin', 'Administrator')])),
                ('description', models.TextField(default='')),
                ('balance_after', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.planorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.user')),
            ],
            options={
                'db_table': 'wallet_transactions',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_wallet_user')],
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('card_number', models.TextField()),
                ('card_holder', models.TextField()),
                ('status', models.TextField(choices=[('pending', "Ko'rib chiqilmoqda"), ('done', "O'tkazildi"), ('rejected', 'Rad etildi')], default='pending')),
                ('note', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.user')),
            ],
            options={
                'db_table': 'withdraw_requests',
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_withdraw_status')],
            },
        ),
    ]
