# Generated by Django 5.2.17 on 2026-09-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdesign',
            name='render_error',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='render_photo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='render_source',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='render_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='render_status',
            field=models.TextField(default=''),
        ),
    ]
