# Generated by Django 5.2.17 on 2026-10-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_design_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdesign',
            name='render_marks',
            field=models.TextField(default=''),
        ),
    ]
