# Generated by Django 5.2.17 on 2026-10-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_design_render_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdesign',
            name='geometry',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='geometry_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='geometry_status',
            field=models.TextField(default=''),
        ),
    ]
