# Generated by Django 5.2.17 on 2026-10-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_design_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdesign',
            name='render_guide',
            field=models.TextField(default=''),
        ),
    ]
