# Generated by Django 5.2.17 on 2026-10-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_design_render_guide'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='otpcode',
            name='otp_codes_purpose_check',
        ),
        migrations.AddConstraint(
            model_name='otpcode',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['register', 'reset', 'login'])), name='otp_codes_purpose_check'),
        ),
    ]
