# Generated by Django 5.2.17 on 2026-10-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_otp_login_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdesign',
            name='variant',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='variant_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='core.roomdesign'),
        ),
    ]
