# Generated by Django 5.2.17 on 2026-10-03 12:58

from django.db import migrations, models
from django.db.models import F


def kind_from_key(apps, schema_editor):
    """Boshlang'ich mahsulotlarning turi — o'z kaliti (3D va xona qoidalari shu bilan topadi)."""
    CatalogItem = apps.get_model("core", "CatalogItem")
    CatalogItem.objects.filter(key__isnull=False).exclude(key="").update(kind=F("key"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_design_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='color',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='cutout',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='image_error',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='image_source',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='kind',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='origin',
            field=models.TextField(choices=[('seed', "Boshlang'ich baza"), ('ai', 'AI qidiruvi'), ('admin', 'Administrator'), ('partner', "Hamkor do'kon")], default='seed'),
        ),
        migrations.RunPython(kind_from_key, migrations.RunPython.noop),
    ]
