# Generated by Django 5.2.17 on 2026-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_catalog_kind_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='origin',
            field=models.TextField(choices=[('seed', "Boshlang'ich baza"), ('ai', 'AI qidiruvi'), ('admin', 'Administrator'), ('partner', "Hamkor do'kon"), ('market', "Do'kon narxi (internet)")], default='seed'),
        ),
    ]
