# Generated by Django 5.2.17 on 2026-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_master_portfolio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planorder',
            name='plan_orders_plan_check',
        ),
        migrations.AddField(
            model_name='master',
            name='plan',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='master',
            name='plan_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='planorder',
            constraint=models.CheckConstraint(condition=models.Q(('plan__in', ['pdf', 'design3d', 'usta_pro', 'usta_top'])), name='plan_orders_plan_check'),
        ),
    ]
