# Generated by Django 5.2.17 on 2026-10-03 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_master_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('region', models.TextField(default='samarqand')),
                ('district', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('phone', models.TextField(default='')),
                ('telegram', models.TextField(default='')),
                ('categories', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('work_hours', models.TextField(default='')),
                ('map_url', models.TextField(default='')),
                ('logo', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shops',
                'indexes': [models.Index(fields=['is_active', 'region', 'district'], name='idx_shops_place')],
            },
        ),
    ]
