# Generated by Django 5.2.17 on 2026-10-03 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('unit', models.TextField(default='dona')),
                ('category', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.shop')),
            ],
            options={
                'db_table': 'shop_products',
                'indexes': [models.Index(fields=['shop', 'category'], name='idx_shop_products')],
            },
        ),
    ]
