# Generated by Django 5.2.17 on 2026-10-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shop_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='document',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='master',
            name='document_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='master',
            name='offer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
