# Generated by Django 5.2.17 on 2026-10-03 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_master_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('status', models.TextField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('used', 'Ishlatildi')], default='pending')),
                ('chat_id', models.TextField(blank=True, null=True)),
                ('is_new_user', models.BooleanField(default=False)),
                ('next_path', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_logins', to='core.user')),
            ],
            options={
                'db_table': 'telegram_logins',
            },
        ),
    ]
